<a href="https://colab.research.google.com/github/SwethaR1505/ML_PJTS/blob/main/Arrayindexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ls=[14,34,56,78,99,200,12.4,5,7.8]

In [3]:
arr=np.array(ls)

In [4]:
arr

array([ 14. ,  34. ,  56. ,  78. ,  99. , 200. ,  12.4,   5. ,   7.8])

In [5]:
arr[0]

14.0

In [6]:
arr[7]

5.0

In [7]:
arr.shape

(9,)

In [8]:
arr[2:5]

array([56., 78., 99.])

In [9]:
arr[3:8] #arr[a:b]

array([ 78. ,  99. , 200. ,  12.4,   5. ])

In [10]:
arr[2]

56.0

In [11]:
arr[1:3]=44

In [12]:
arr

array([ 14. ,  44. ,  44. ,  78. ,  99. , 200. ,  12.4,   5. ,   7.8])

In [13]:
array_slice=arr[3:8]

In [14]:
array_slice

array([ 78. ,  99. , 200. ,  12.4,   5. ])

In [15]:
array_slice[1:]

array([ 99. , 200. ,  12.4,   5. ])

In [16]:
array_slice[:]=-1

In [17]:
array_slice

array([-1., -1., -1., -1., -1.])

In [18]:
arr

array([14. , 44. , 44. , -1. , -1. , -1. , -1. , -1. ,  7.8])

In [19]:
arrw=arr.copy()

In [20]:
arrw[3]=56

In [21]:
arrw

array([14. , 44. , 44. , 56. , -1. , -1. , -1. , -1. ,  7.8])

In [22]:
arr=np.arange(90)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [24]:
arr=arr.reshape(9,10)

In [25]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [26]:
arr.shape

(9, 10)

In [27]:
arr[1,1]

11

In [28]:
arr[2,3]

23

In [29]:
arr[5,5]

55

In [30]:
arr[6,7]

67

In [31]:
# multidimensional arrays
arr[1][4]


14

In [32]:
arr[2][4]

24

In [33]:
arr=arr.reshape(9,2,5)

In [34]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [35]:
arr[7]

array([[70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79]])

In [36]:
arr[3][0]

array([30, 31, 32, 33, 34])