<a href="https://colab.research.google.com/github/SwethaR1505/ML_PJTS/blob/main/arrayoprators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
b=np.random.random((3,3))

In [3]:
c=np.random.random((3,3))

In [4]:
b

array([[0.4634772 , 0.29802192, 0.49970748],
       [0.62281661, 0.00204901, 0.45844214],
       [0.55348073, 0.80319808, 0.27895861]])

In [5]:
c

array([[0.21332736, 0.42096375, 0.40758169],
       [0.98724201, 0.93048232, 0.65443949],
       [0.7787016 , 0.91465215, 0.91929136]])

In [6]:
b + c

array([[0.67680456, 0.71898567, 0.90728916],
       [1.61005863, 0.93253133, 1.11288162],
       [1.33218233, 1.71785024, 1.19824997]])

In [7]:
b -c

array([[ 0.25014985, -0.12294184,  0.09212579],
       [-0.3644254 , -0.92843332, -0.19599735],
       [-0.22522087, -0.11145407, -0.64033275]])

In [8]:
b*c

array([[0.09887237, 0.12545642, 0.20367162],
       [0.61487073, 0.00190657, 0.30002264],
       [0.43099633, 0.73464686, 0.25644424]])

In [9]:
b/c

array([[2.17261026, 0.70795149, 1.22603025],
       [0.63086518, 0.00220209, 0.70051112],
       [0.71077384, 0.87814595, 0.30344962]])

In [10]:
b%c

array([[0.03682249, 0.29802192, 0.09212579],
       [0.62281661, 0.00204901, 0.45844214],
       [0.55348073, 0.80319808, 0.27895861]])

In [11]:
1/c

array([[4.68763134, 2.37550144, 2.4534959 ],
       [1.01292286, 1.07471144, 1.52802516],
       [1.28418896, 1.09331181, 1.08779441]])

In [12]:
2/b

array([[  4.31520684,   6.71091586,   4.00234156],
       [  3.21121812, 976.08202998,   4.36260071],
       [  3.61349528,   2.49004579,   7.16952238]])

In [13]:
b += c #b=b+c

In [14]:
b

array([[0.67680456, 0.71898567, 0.90728916],
       [1.61005863, 0.93253133, 1.11288162],
       [1.33218233, 1.71785024, 1.19824997]])

In [15]:
 b**2

array([[0.45806441, 0.51694039, 0.82317363],
       [2.59228879, 0.86961468, 1.23850551],
       [1.77470976, 2.95100943, 1.43580299]])

In [16]:
0.52522541 *0.52522541

0.2758617313096681

In [17]:
1.45346678 * 1.45346678

2.1125656805635686