<a href="https://colab.research.google.com/github/SwethaR1505/ML_PJTS/blob/main/arraystatistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[-0.36028233, -1.28447653, -1.2941907 , -0.39352281],
       [-0.16717845, -0.79696478,  0.04337812, -0.17699833],
       [-0.18403912,  0.09021891,  0.3437557 , -0.5014089 ],
       [-2.35016226,  0.93752102, -0.47240761,  0.29915826]])

In [4]:
arr.sum()

-6.2675998148865215

In [5]:
arr.mean()

-0.3917249884304076

In [6]:
arr.var()

0.561066925123979

In [7]:
arr.std()

0.7490440074681721

In [8]:
np.where(arr<0)


(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 3, 0, 3, 0, 2]))

In [9]:
np.where(arr<0,0,arr)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.04337812, 0.        ],
       [0.        , 0.09021891, 0.3437557 , 0.        ],
       [0.        , 0.93752102, 0.        , 0.29915826]])

In [10]:
arr.sort()

In [11]:
arr

array([[-1.2941907 , -1.28447653, -0.39352281, -0.36028233],
       [-0.79696478, -0.17699833, -0.16717845,  0.04337812],
       [-0.5014089 , -0.18403912,  0.09021891,  0.3437557 ],
       [-2.35016226, -0.47240761,  0.29915826,  0.93752102]])