<a href="https://colab.research.google.com/github/SwethaR1505/ML_PJTS/blob/main/arrayFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
np.random.randint(12)

3

In [5]:
arr1=np.random.randn(12)

In [6]:
arr1

array([ 0.59416542, -0.47928126,  0.22716832, -0.69354103,  0.1772666 ,
        0.78655583, -1.00145225,  0.07193503, -0.11612422, -1.17807205,
       -1.0857957 , -1.1773654 ])

In [7]:
np.sqrt(arr1)

<ipython-input-7-31bdbbe4b4c3>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([0.77082126,        nan, 0.47662178,        nan, 0.4210304 ,
       0.88687983,        nan, 0.26820707,        nan,        nan,
              nan,        nan])

In [8]:
np.exp(arr1)

array([1.81151846, 0.61922829, 1.2550411 , 0.49980311, 1.19394935,
       2.19582062, 0.36734558, 1.07458553, 0.89036462, 0.30787173,
       0.33763302, 0.30808936])

In [9]:
arr2=np.random.randn(12)

In [10]:
arr2

array([-0.74183502,  1.78005766, -0.35268111,  0.91303388,  0.21862578,
        1.12794485, -1.11982911, -0.25148693, -0.56624532, -0.9560084 ,
       -0.54131994,  0.66425528])

In [11]:
np.add(arr1,arr2)

array([-0.1476696 ,  1.30077639, -0.12551279,  0.21949285,  0.39589238,
        1.91450068, -2.12128136, -0.17955189, -0.68236954, -2.13408045,
       -1.62711564, -0.51311012])

In [12]:
np.minimum(arr1,arr2)

array([-0.74183502, -0.47928126, -0.35268111, -0.69354103,  0.1772666 ,
        0.78655583, -1.11982911, -0.25148693, -0.56624532, -1.17807205,
       -1.0857957 , -1.1773654 ])

In [13]:
np.maximum(arr1,arr2)

array([ 0.59416542,  1.78005766,  0.22716832,  0.91303388,  0.21862578,
        1.12794485, -1.00145225,  0.07193503, -0.11612422, -0.9560084 ,
       -0.54131994,  0.66425528])